ksql_listener_port: 8088

ksql:
  config_file: /etc/ksql/ksql-server.properties
  service_name: confluent-ksql
  systemd_override: /etc/systemd/system/confluent-ksql.service.d
  user: cp-ksql
  group: confluent
  streams_state_dir: /var/lib/kafka-streams
  environment:
    KSQL_HEAP_OPTS: "-Xmx3g"
  config:
    application.id: ksql-server
    consumer.interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
    producer.interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
    ksql.streams.replication.factor: 3
    ksql.sink.replicas: 3
    ksql.streams.num.standby.replicas: 1
    ksql.streams.state.dir: /var/lib/kafka-streams
    listeners: http://0.0.0.0:{{ksql_listener_port}}
    ssl.endpoint.identification.algorithm: ""
    ksql.schema.registry.enable: true
  systemd:
    enabled: yes
    state: started
